domain/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

domain/force-app/main/default/objects/Contact_Aggregate__c/Contact_Aggregate__c.object-meta.xml
<CustomObject>
    <label>Contact Aggregate</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Contact Aggregate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Aggregate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

domain/force-app/main/default/objects/Contact_Aggregate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts Aggregate</relationshipLabel>
    <relationshipName>Contacts_Aggregate</relationshipName>
    <type>Lookup</type>
</CustomField>

domain/force-app/main/default/objects/Contact_Aggregate__c/fields/Composite_Key__c.field-meta.xml
<CustomField>
    <fullName>Composite_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Composite Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

domain/force-app/main/default/objects/Contact_Aggregate__c/fields/Number_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contacts__c</fullName>
    <label>Number of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

domain/force-app/main/default/objects/Contact_Aggregate__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

domain/force-app/main/default/objects/Contact_Aggregate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

domain/force-app/main/default/classes/ContactAggregatorController.cls
public with sharing class ContactAggregatorController {

    @AuraEnabled(cacheable=true)
    public static List<AggregateDTO> getAggregatedContactData(Id accountId) {
        List<AggregateDTO> result = new List<AggregateDTO>();

        AggregateResult[] groupedResults = [
            SELECT Type__c, MailingState, COUNT(Id) cn
            FROM Contact
            WHERE AccountId = :accountId
            GROUP BY Type__c, MailingState
        ];

        for (AggregateResult ar : groupedResults) {
            result.add(new AggregateDTO(
                (String)ar.get('Type__c'),
                (String)ar.get('MailingState'),
                (Integer)ar.get('cn'),
                accountId
            ));
        }

        return result;
    }

    @AuraEnabled
    public static void saveSelections(Id accountId, List<AggregateDTO> selections) {
        List<Contact_Aggregate__c> toUpsert = new List<Contact_Aggregate__c>();
        for(AggregateDTO selected : selections){
            system.debug('==>'+selected);
            Contact_Aggregate__c ca = new Contact_Aggregate__c();
            ca.Account__c = accountId;
            ca.State__c = selected.state;
            ca.Type__c =  selected.type;
            ca.Number_of_Contacts__c = selected.Count ;
            ca.Composite_Key__c = accountId + '||' + selected.state+ '||' + selected.type;
            toUpsert.add(ca);
        }       

        try {
            upsert toUpsert Composite_Key__c ;
        } catch (DmlException e) {
            throw new AuraHandledException('Validation Error: ' + e.getMessage());
        }
    }

    public class AggregateDTO {
        @AuraEnabled public String Type { get; set; }
        @AuraEnabled public String State{ get; set; }
        @AuraEnabled public Integer Count{ get; set; }
        @AuraEnabled public String id;

        public AggregateDTO(String type, String state, Integer count,string accountId) {
            this.Type = type;
            this.State = state;
            this.Count = count;
            this.id = accountId + '||' + state+ '||' + type;
        }
        public AggregateDTO(){
        }
    }
}